<a href="https://colab.research.google.com/github/HKyeol/team_study/blob/main/%EA%B0%80%EC%A7%9C%ED%95%B4%EB%B0%80%ED%86%A0%EB%8B%88%EC%95%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

svd

In [ ]:
import numpy as np
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
a = [[0 for i in range(7)] for i in range(7)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
#matA = np.array(a).astype(np.float64)
U,s,V = np.linalg.svd(a, full_matrices = True)

# s는 matA의 고유값(eigenvalue) 리스트이다.
 # svd를 이용하여 근사한(approximated) 결과를 원본과 비교하기 위해
 # s를 유사대각행렬로 변환한다.
 # 유사행렬에 대한 내용은 이전 포스트 참조.
S = np.zeros(matA.shape)
for i in range(len(s)):
    S[i][i] = s[i]
# 근사한 결과를 계산한다.
appA = np.dot(U, np.dot(S, V))
print(U)
print(S)
print(V)

 # 원래 행렬인 matA와 근사한 행렬인 appA가 서로 비슷하다면
 # 두 행렬의 차이는 영행렬(zero matrix)에 가까울 것이다.
 # 즉, 다음의 결과가 대부분 0으로 채워져있다면 성공적인 svd가 이루어진 것이다.
 # 파이썬 버전에 따라 출력방식이 다르므로 주의한다.
 # case : python2 사용자
 # case : python3 사용자

#print(matA - appA)

In [75]:
import numpy as np
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
a = [[0 for i in range(7)] for i in range(7)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
eigenvalue, eigenvector = np.linalg.eig(a)
print(eigenvector)
#II = np.identity(n=7, dtype=np.int8)*2
np.dot(eigenvalue,eigenvalue)

[[-1.61229842e-01 -1.61229842e-01  4.64242827e-01  4.64242827e-01
  -3.03012985e-01 -5.77350269e-01  3.03012985e-01]
 [-3.03012985e-01 -3.03012985e-01 -1.61229842e-01 -1.61229842e-01
   4.64242827e-01 -5.77350269e-01 -4.64242827e-01]
 [-4.64242827e-01 -4.64242827e-01  3.03012985e-01  3.03012985e-01
   1.61229842e-01  5.77350269e-01 -1.61229842e-01]
 [-4.08248290e-01 -4.08248290e-01 -4.08248290e-01 -4.08248290e-01
  -4.08248290e-01  2.00032731e-16  4.08248290e-01]
 [-3.17560796e-01  3.17560796e-01  5.96819074e-01 -5.96819074e-01
   2.07273089e-01 -1.66259903e-16  2.07273089e-01]
 [-5.96819074e-01  5.96819074e-01 -2.07273089e-01  2.07273089e-01
  -3.17560796e-01 -1.74055935e-16 -3.17560796e-01]
 [-2.07273089e-01  2.07273089e-01 -3.17560796e-01  3.17560796e-01
   5.96819074e-01 -7.45894213e-17  5.96819074e-01]]


11.999999999999977

행렬맛보기

In [240]:
import numpy as np
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
a = [[0 for i in range(7)] for i in range(7)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
b = a

#for k in range(2):
for k in range(0,7):
    a = [[0 for i in range(7)] for i in range(7)]
    a = np.array(a)
    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1
    print('')
    print(f'{k}부터 시작해서 7번')
    print(' 0,1,2,3,4,5,6')
    a = a[k,:]
    for j in range(7):
        print(a)
        a = np.dot(a,b)
print(b)




0부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 1 0 0]
[1 0 1 0 0 0 0]
[0 0 0 0 2 1 0]
[2 1 3 1 0 0 0]
[0 0 0 0 5 5 1]
[ 5  5 10  6  0  0  0]
[ 0  0  0  0 15 21  6]

1부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 0 1 0]
[0 1 1 1 0 0 0]
[0 0 0 0 1 3 1]
[1 3 4 4 0 0 0]
[ 0  0  0  0  5 11  4]
[ 5 11 16 15  0  0  0]
[ 0  0  0  0 21 42 15]

2부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 1 1 0]
[1 1 2 1 0 0 0]
[0 0 0 0 3 4 1]
[3 4 7 5 0 0 0]
[ 0  0  0  0 10 16  5]
[10 16 26 21  0  0  0]
[ 0  0  0  0 36 63 21]

3부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 0 1 1]
[0 1 1 2 0 0 0]
[0 0 0 0 1 4 2]
[1 4 5 6 0 0 0]
[ 0  0  0  0  6 15  6]
[ 6 15 21 21  0  0  0]
[ 0  0  0  0 27 57 21]

4부터 시작해서 7번
 0,1,2,3,4,5,6
[1 0 1 0 0 0 0]
[0 0 0 0 2 1 0]
[2 1 3 1 0 0 0]
[0 0 0 0 5 5 1]
[ 5  5 10  6  0  0  0]
[ 0  0  0  0 15 21  6]
[15 21 36 27  0  0  0]

5부터 시작해서 7번
 0,1,2,3,4,5,6
[0 1 1 1 0 0 0]
[0 0 0 0 1 3 1]
[1 3 4 4 0 0 0]
[ 0  0  0  0  5 11  4]
[ 5 11 16 15  0  0  0]
[ 0  0  0  0 21 42 15]
[21 42 63 57  0  0  0]

6부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0

In [239]:
import numpy as np
t = [[2,5],[2,0],[3,2],[4,2],[2,1]]
a = [[0 for i in range(6)] for i in range(6)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
b = a

#for i in range(4):
#    print(a)
#    a = np.dot(a,b)
for k in range(0,6):
    a = [[0 for i in range(6)] for i in range(6)]
    a = np.array(a)
    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1
    print('')
    print(f'{k}부터 시작해서 7번')
    print(' 0,1,2,3,4,5,6')
    a = a[k,:]
    for j in range(6):
        print(a)
        a = np.dot(a,b)
print(b)


0부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 1 0 0 0]
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]

1부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 1 0 0 0]
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]

2부터 시작해서 7번
 0,1,2,3,4,5,6
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]
[  0   0 125   0   0   0]

3부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 1 0 0 0]
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]

4부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 1 0 0 0]
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]

5부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 1 0 0 0]
[1 1 0 1 1 1]
[0 0 5 0 0 0]
[5 5 0 5 5 5]
[ 0  0 25  0  0  0]
[25 25  0 25 25 25]
[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [1 1 0 1 1 1]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]]


다리 삭제버전

In [ ]:
import numpy as np
t = [[2,5],[2,0],[3,2],[4,2],[2,1]]
a = [[0 for i in range(6)] for i in range(6)]

check = [0 for i in range(6)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
b = a
#for i in range(4):
#    print(a)
#    a = np.dot(a,b)
for k in range(0,6):
    a = [[0 for i in range(6)] for i in range(6)]
    check = [0 for i in range(6)]
    a = np.array(a)

    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1

    b = a

    print('')
    print(f'{k}부터 시작해서 7번')
    
    print(' 0,1,2,3,4,5,6')
    a = a[k,:]
    check = [0 for i in range(6)]
#    print(a)
    for j in range(6):

        for q in range(0,len(a)):
            if a[q] != 0:
                check[q] += int(a[q]/a[q])
#        print(np.array(check))
        for w in range(0,len(check)):
            if check[w] == 2:
                b[w,:] = 0
                b[:,w] = 0
        print(a,b)

        a = np.dot(a,b)

print(b)

In [163]:
import numpy as np
t = [[2,5],[2,0],[3,2],[4,2],[2,1]]
a = [[0 for i in range(6)] for i in range(6)]
check = [0 for i in range(6)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
b = a
b[2,:] = 0
b[:,2] = 0
b

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

정리하자

In [ ]:
import numpy as np
t = [[2,5],[2,0],[3,2],[4,2],[2,1]]
a = [[0 for i in range(6)] for i in range(6)]

check = [[0 for i in range(6)] for i in range(6)]
a = np.array(a)
#print(a[5,1])
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
b = a
#for i in range(4):
#    print(a)
#    a = np.dot(a,b)
for k in range(0,6):
    a = [[0 for i in range(6)] for i in range(6)]
    check = [[0 for i in range(6)] for i in range(6)]
    a = np.array(a)
    check = np.array(check)
    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1

    b = a
#    print(check)
    print('')
    print(f'{k}부터 시작해서 7번')
    
    print(' 0,1,2,3,4,5,6')

    for j in range(6):

        for q in range(0,len(a)):
            for q2 in range(0,len(a)):
                if a[q,q2] != 0:
                    check[q,q2] += a[q,q2]/a[q,q2]
#        print(np.array(check))
        for w in range(0,len(check)):
#        for w2 in range(0,len(check)):
            if 2 in check[w,:]:         # check[w,w2] == 2:
                b[w,:] = 0
                b[:,w] = 0
#        print(check,'체크 \n', a,'드럽게힘드네',b)   

        a = np.dot(a,b)
        print(a)
print(b)

In [272]:
import numpy as np
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]

for k in range(0,7):
    a = [[0 for i in range(7)] for i in range(7)]
    a = np.array(a)
    check = [0 for i in range(7)]
    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1
    b = a


    print('')
    print(f'{k}부터 시작해서 7번')
    print(' 0,1,2,3,4,5,6')
    a = a[k,:]
    for j in range(9):

        for q in range(0,len(a)):
            if a[q] != 0:
                check[q] += a[q]/a[q]
#        print(check)    
        for w in range(0,len(check)):
            if check[w] == 2:
#            if 2 in check:         # check[w,w2] == 2:
#                b[w,:] = 0
                b[:,w] = 0

        print(a)
#        print(b)
#        print(' ')
#        print(f'{j+2}번째')

        a = np.dot(a,b)



0부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 1 0 0]
[1 0 1 0 0 0 0]
[0 0 0 0 2 1 0]
[2 1 3 1 0 0 0]
[0 0 0 0 0 5 1]
[0 5 0 6 0 0 0]
[0 0 0 0 0 0 6]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]

1부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 0 1 0]
[0 1 1 1 0 0 0]
[0 0 0 0 1 3 1]
[1 3 4 4 0 0 0]
[0 0 0 0 5 0 4]
[5 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]

2부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 1 1 0]
[1 1 2 1 0 0 0]
[0 0 0 0 3 4 1]
[3 4 7 5 0 0 0]
[0 0 0 0 0 0 5]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]

3부터 시작해서 7번
 0,1,2,3,4,5,6
[0 0 0 0 0 1 1]
[0 1 1 2 0 0 0]
[0 0 0 0 1 4 2]
[1 4 5 6 0 0 0]
[0 0 0 0 6 0 0]
[6 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]

4부터 시작해서 7번
 0,1,2,3,4,5,6
[1 0 1 0 0 0 0]
[0 0 0 0 2 1 0]
[2 1 3 1 0 0 0]
[0 0 0 0 5 5 1]
[0 5 0 6 0 0 0]
[0 0 0 0 0 0 6]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]

5부터 시작해서 7번
 0,1,2,3,4,5,6
[0 1 1 1 0 0 0]
[0 0 0 0 1 3 1]
[1 3 4 4 0 0 0]
[ 0  0  0  0  5 11  4]
[5 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 

In [256]:
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
a = [[0 for i in range(7)] for i in range(7)]
a = np.array(a)
for i in t:
    a[i[0],i[1]] = 1
    a[i[1],i[0]] = 1
print(a)
print(a[2,:])

[[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 0 0 0 1 1 0]


1차답안 # 실패! 모든 경로를 1번은 거쳐야 한다.

In [315]:
import numpy as np
def solution(t):
    t1 = []
    cnt_list = []
    cnt = 0
    for q in range(len(t)):
        for q2 in t[q]:
            t1.append(q2)
    num1 = max(t1)


    for k in range(0,num1+1):
        a = [[0 for i in range(num1+1)] for i in range(num1+1)]
        a = np.array(a)
        check = [0 for i in range(num1+1)]
        for i in t:
            a[i[0],i[1]] = 1
            a[i[1],i[0]] = 1
        b = a

        a = a[k,:]
        cnt_list.append(cnt)
        cnt = 0

        
        for j in range((num1+1)*2):

            for q in range(0,len(a)):
                if a[q] != 0:
                    check[q] += a[q]/a[q]

            for w in range(0,len(check)):
                if check[w] == 2:

                    b[:,w] = 0

            if sum(a) != 0:
                cnt += 1
            else:
                break
            a = np.dot(a,b)
    return max(cnt_list)

#t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
t = [[2,5],[2,0],[3,2],[4,2],[2,1]]
solution(t)


4

In [312]:
t = [[5,1],[2,5],[3,5],[3,6],[2,4],[4,0]]
t1 = []
cnt_list = []

for q in range(len(t)):
    for q2 in t[q]:
        t1.append(q2)
num1 = max(t1)


for k in range(0,num1+1):
    a = [[0 for i in range(num1+1)] for i in range(num1+1)]
    a = np.array(a)
    check = [0 for i in range(num1+1)]
    for i in t:
        a[i[0],i[1]] = 1
        a[i[1],i[0]] = 1
    b = a

    a = a[k,:]
    cnt_list.append(cnt)

    cnt = 0
    
    for j in range((num1+1)*2):

        for q in range(0,len(a)):
            if a[q] != 0:
                check[q] += a[q]/a[q]

        for w in range(0,len(check)):
            if check[w] == 2:

                b[:,w] = 0

        if sum(a) != 0:
            cnt += 1
        else:
            break
        a = np.dot(a,b)
cnt_list

[0 0 0 0 1 0 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 0 0 0 0 1 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 0 0 0 1 1 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 0 0 0 0 1 1] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[1 0 1 0 0 0 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 1 1 1 0 0 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]
[0 0 0 1 0 0 0] [[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0]]


[0, 0, 0, 0, 0, 0, 0]